#pragma once

#include "operation.h"
#include "variable.h"
#include "big_null.h"
#include "func.h"
#include "disjunction.h"
#include "increment.h"
#include "multiplied.h"
#include "summand.h"
#include "predicate.h"
#include "equals.h"
#include "substitution.h"
#include "negation.h"
#include "every.h"
#include "exist.h"
#include "consequence.h"
#include "conjunction.h"
#include "arrays.h"
#include <map>
#include <set>
#include <memory>
#include <iostream>